version: 2
jobs:
  test:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./test_all.sh
workflows:
  version: 2
  build_and_release:
    jobs:
      - test
