version: 2
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          command: |
            ./test_all.sh
workflows:
  version: 2
  build_and_release:
    jobs:
      - test
